- README.md
This badge links to our careers page to encourage contributors / users to join our team.
[![CLARK Open Source](https://img.shields.io/badge/CLARK-Open%20Source-%232B6CDE.svg)](https://www.clark.de/de/jobs)
> docs(README): add CLARK open source badge

- k8t/cluster.py
- k8t/environment.py
- k8t/project.py
cleaner behaviour, less clutter when starting a new project
> [#29] don't create empty directories when using scaffolding commands

- k8t/cli.py
> [#24] support value options on validation command

- k8t/cli.py
- k8t/engine.py
- k8t/filters.py
- k8t/util.py
- tests/engine.py
- tests/filters.py
- tests/templates.py
- tests/util.py
also moved jinja filters to separate file
> [#23] fail properly for undefined values instead of templating empty string

- k8t/assets/configmap.yaml.j2
- k8t/assets/cronjob.yaml.j2
- k8t/assets/deployment.yaml.j2
- k8t/assets/ingress.yaml.j2
- k8t/assets/job.yaml.j2
- k8t/assets/namespace.yaml.j2
- k8t/assets/pod.yaml.j2
- k8t/assets/secret.yaml.j2
- k8t/assets/service.yaml.j2
- k8t/assets/serviceaccount.yaml.j2
* configmap
* cronjob
* ingress
* job
* pod
* secret
* serviceaccount
> [#35] add missing templates

- k8t/cli.py
- k8t/secret_providers.py
- tests/secret_providers.py
> [#39] add random secrets provider with session store

- README.md
- examples/README.md
- examples/single-cluster/README.md
- examples/single-cluster/config.yaml
- examples/single-cluster/environments/production/config.yaml
- examples/single-cluster/environments/production/templates/hello-world-ingress.yaml.j2
- examples/single-cluster/environments/production/values.yaml
- examples/single-cluster/templates/hello-world-deployment.yaml.j2
- examples/single-cluster/templates/hello-world-secret.yaml.j2
- examples/single-cluster/templates/hello-world-service.yaml.j2
- examples/single-cluster/values.yaml
I added a basic example and tried to improve the Readme. Please let me know what you think and if there is something I should improve/add.
Closes #36
> [#33] improve documentation

- README.md
- k8t/cli.py
use click helper function instead
Closes #42
> [#42] replace own file edit command with clicks

- .github/release-drafter.yml
> [CLOUD-1013] release-drafter config added

- k8t/values.py
> feature(templates): add cluster/environment to template values

- README.md
- k8t/engine.py
- k8t/filters.py
- tests/filters.py
Add `bool` filter to be able to cast cli values to boolean.
https://github.com/ClarkSource/k8t/issues/52
> Bool filter

- .pylintrc
- k8t/cli.py
- setup.cfg
https://github.com/ClarkSource/k8t/issues/41
> Replace termcolor with click color support

- Dockerfile
* kubectl
* curl, openssl, gzip, tar, bash, ca-certificates
> install tools on container

- default.nix
- k8t/cli.py
- k8t/filters.py
alternative solution to https://github.com/ClarkSource/k8t/pull/65
> Secret provider

- .envrc
- .gitignore
- .pre-commit-config.yaml
- README.md
- default.nix
- k8t/templates.py
* filter guarded variables (`foobar is defined` should now work)
* filter local variables (`{% set foobar = ".." %}` now works consitently)
* properly parse node arguments in validation
this resolves #76
> several improvements to variable validation

- Jenkinsfile
- README.md
- default.nix
- k8t/cli.py
- k8t/util.py
- setup.cfg
- setup.py
this allows passing structure values via cli as json `--value deployment '{"image_tag": "latest"}'`
> can now pass structured values via cli as json

- k8t/cluster.py
> fix cluster search function

- .envrc
- default.nix
- k8t/cli.py
- pyproject.toml
- setup.cfg
resolves https://github.com/ClarkSource/k8t/issues/87
> filter template file names

- CHANGELOG.txt
- Dockerfile
- README.md
> add kubeval to docker image and verify tooling checksums

- README.md
- examples/single-cluster/templates/hello-world-deployment.yaml.j2
- examples/single-cluster/templates/hello-world-secret.yaml.j2
- examples/single-cluster/templates/hello-world-service.yaml.j2
- k8t/engine.py
- k8t/filters.py
- tests/filters.py
can be used like
```yaml
labels:
mylabel: "{{ mylabel_value | sanitize_label }}"
```
and replaces invalid characters with uppercase `X`
> feat(filters): add sanitization function for labels

- .github/workflows/codeql-analysis.yml
- README.md
- k8t/cli.py
- k8t/secret_providers.py
adds a new secrets provider that ensures static secrets for testing/validation purposes
> feat: hashing secrets provider added

- Dockerfile
> fix: install awscli via pip due to errors

- k8t/cli.py
- k8t/templates.py
- k8t/util.py
- setup.cfg
- tox.ini
fixes #108
adds a command to print the merged values
also switched from PyYaml to ruamel.yaml for better formatting
> feat: allow printing merged value set

- .pre-commit-config.yaml
- Dockerfile
- k8t/engine.py
- k8t/filters.py
- k8t/util.py
- setup.cfg
- tests/filters.py
add resource sanitization functions
* sanitize_cpu -> to millis in kubernetes notation
* sanitize_memory -> to MB in kubernetes notation
and standardization functions
* standardize_cpu -> to millis as int
* standardize_memory -> to MB as int
to be used like there: https://github.com/ClarkSource/application/pull/18570
> [RFC] feat(resource sanitization): add filters

- .pre-commit-hooks.yaml
- Dockerfile
- README.md
- pre_commit_hooks/k8t-generate
pulling commit from https://github.com/ClarkSource/k8t/pull/119 (cherry-picked and squashed)
contribution by @gozer
> Add pre-commit validate hook
